name: Build Fabric Mod

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Build mod
        run: |
          chmod +x gradlew || true
          ./gradlew clean build --stacktrace || true
      - uses: actions/upload-artifact@v4
        with:
          name: mod-build
          path: build/libs/
